/**
 * Custom providers configuration
 * These providers will be injected into the models snapshot during build
 */

export const customProviders = {
  /**
   * Bailian Coding Plan - Alibaba Cloud DashScope
   * Documentation: https://help.aliyun.com/document_detail/2870896.html
   */
  "bailian-coding-plan": {
    id: "bailian-coding-plan",
    name: "Model Studio Coding Plan",
    env: ["BAILIAN_CODING_API_KEY"],
    npm: "@ai-sdk/anthropic",
    api: "https://coding.dashscope.aliyuncs.com/apps/anthropic/v1",
    models: {
      "qwen3.5-plus": {
        id: "qwen3.5-plus",
        name: "Qwen3.5 Plus",
        family: "qwen",
        release_date: "2025-01-01",
        attachment: true,
        reasoning: true,
        temperature: true,
        tool_call: true,
        modalities: { input: ["text", "image"], output: ["text"] },
        cost: { input: 0, output: 0 },
        limit: { context: 128000, output: 8192 },
      },
      "qwen3-max-2026-01-23": {
        id: "qwen3-max-2026-01-23",
        name: "Qwen3 Max 2026-01-23",
        family: "qwen",
        release_date: "2026-01-23",
        attachment: true,
        reasoning: true,
        temperature: true,
        tool_call: true,
        cost: { input: 0, output: 0 },
        limit: { context: 128000, output: 8192 },
      },
      "qwen3-coder-next": {
        id: "qwen3-coder-next",
        name: "Qwen3 Coder Next",
        family: "qwen",
        release_date: "2025-01-01",
        attachment: true,
        reasoning: true,
        temperature: true,
        tool_call: true,
        cost: { input: 0, output: 0 },
        limit: { context: 128000, output: 8192 },
      },
      "qwen3-coder-plus": {
        id: "qwen3-coder-plus",
        name: "Qwen3 Coder Plus",
        family: "qwen",
        release_date: "2025-01-01",
        attachment: true,
        reasoning: true,
        temperature: true,
        tool_call: true,
        cost: { input: 0, output: 0 },
        limit: { context: 128000, output: 8192 },
      },
      "MiniMax-M2.5": {
        id: "MiniMax-M2.5",
        name: "MiniMax M2.5",
        family: "minimax",
        release_date: "2025-01-01",
        attachment: true,
        reasoning: true,
        temperature: true,
        tool_call: true,
        cost: { input: 0, output: 0 },
        limit: { context: 128000, output: 8192 },
      },
      "glm-5": {
        id: "glm-5",
        name: "GLM-5",
        family: "glm",
        release_date: "2025-01-01",
        attachment: true,
        reasoning: true,
        temperature: true,
        tool_call: true,
        cost: { input: 0, output: 0 },
        limit: { context: 128000, output: 8192 },
      },
      "glm-4.7": {
        id: "glm-4.7",
        name: "GLM-4.7",
        family: "glm",
        release_date: "2025-01-01",
        attachment: true,
        reasoning: true,
        temperature: true,
        tool_call: true,
        cost: { input: 0, output: 0 },
        limit: { context: 128000, output: 8192 },
      },
      "kimi-k2.5": {
        id: "kimi-k2.5",
        name: "Kimi K2.5",
        family: "kimi",
        release_date: "2025-01-01",
        attachment: true,
        reasoning: true,
        temperature: true,
        tool_call: true,
        modalities: { input: ["text", "image"], output: ["text"] },
        cost: { input: 0, output: 0 },
        limit: { context: 128000, output: 8192 },
      },
    },
  },
} as const

export type CustomProviders = typeof customProviders